### ISSUE TITLE
[Core] Sensitive data encryption - jasypt

### ISSUE THREAD

**Issue by lstefaniszyn** [devonfw/devonfw-testing#12]

**Comment by lstefaniszyn** [comment]
Jasyp lib

https://bitbucket.org/capntc/selenium_workshop/src/6e976916adfc96c444d99d846b6b49856c4f912e/src/main/java/com/example/core/SecuredProperties.java?at=develop&fileviewer=file-view-default#SecuredProperties.java-10:11

**Comment by marpuch** [comment]
This is part of the feature/security pull request.
